language: go

go:
- "1.12.x"

addons:
  apt:
    packages:
      - libzmq3-dev

sudo: false

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
